stages:
  - test
  - build
  - publish

test:
  image: python:3.11
  stage: test
  script:
    - python -m pip install --upgrade pip
    - pip install pytest
    - pytest -q

build:
  image: python:3.11
  stage: build
  script:
    - python -m pip install --upgrade pip build
    - python -m build
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz

publish:
  image: python:3.11
  stage: publish
  dependencies:
    - build
  only:
    - tags
  script:
    - python -m pip install --upgrade pip twine
    - python -m twine upload -u __token__ -p "$PYPI_TOKEN" dist/*